config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', as: 'home'
  get 'static_pages/about_project', as: 'about_project'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :product_categories
    resources :cart_items, only: [:create, :update, :destroy]
    resources :carts, only: [:show]
    resources :orders, only: [:index, :show, :create]
    get     'customers',          to: 'admins#index',   as: 'users'
    get     'customer/:id',       to: 'admins#show',    as: 'user'
    get     'customer/:id/edit',  to: 'admins#edit',    as: 'user_edit'
    put     'customer/:id',       to: 'admins#update',  as: 'user_update'
    delete  'customer/:id',       to: 'admins#destroy', as: 'user_destroy'
    
    post  'csv_accept',   to: 'products#csv_accept'
    put   'bulk_update',  to: 'products#bulk_update'
    get   'csv_export',   to: 'products#csv_export'

    devise_for :users, controllers: {
      confirmations:  'users/confirmations', 
      passwords:      'users/passwords', 
      registrations:  'users/registrations',
      sessions:       'users/sessions'
    }
    root "static_pages#home"
    resources :products do
      member do
        delete :purge_one_attachment
        delete :purge_all_attachments
      end 
    end
  end
  # delete 'PurgeAttachments/:id/purge', to: 'purge_attachments#purge_one_attachment', as: 'purge_one_attachment'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/views/admins/_users_table.html.erb
<hr>
<div class="users">
  <% @users.each do |user| %>
    <ul class="user_info">
      <li><%= "Id/email: #{user.id}/#{user.email}" %></li>
      <li><%= "#{t('.created_at')}: #{user.created_at}" %></li>
      <li><%= "#{t('.roles')}: #{user.roles.pluck(:name).sort}" %></li>
      <li><%= link_to t('buttons.edit'), user_edit_path(user) %></li>
    </ul>
    <div class="user_orders">
      <% if user.orders.any? %>
        <%= link_to "#{t('.quantity_of_orders')} (#{user.orders.size})", orders_path(user_id: user.id) %>
        <% user.orders.reverse.first(5).each do |order|  %>
          <div><%= link_to "#{t('.date')}: #{order.created_at.strftime("%d/%m/%Y %k:%M")} # #{t('.cost')}: #{order.cost}", order_path(order) %></div>
        <% end %>
      <% else %>
        <%= t('.no_order') %>
      <% end %>
    </div>
    <div class="user_block">
      <%= button_to t('.block_account'), user_update_path(user), params: {set_user_role: :blocked}, form: { data: { confirm: t('.confirmation') } }, method: :put %>
    </div>
    <hr>
  <% end %>

app/views/admins/edit.html.erb
<h2> <%= t('.user') %> <%= @user.email %></h2>
  
<%= simple_form_for @user, url: user_update_path(@user), html: { method: :put } do |f| %>
  <div class="form-inputs">
  <%= f.association :roles, as: :check_boxes %>
    
  <div class="form-actions btn-container btn-width-450">
    <%= f.button :submit, t('.update_roles'), class: 'submit-btn' %>
  </div>
<% end %>

<%= link_to t('buttons.back'), :back %>

app/views/admins/index.html.erb
<h1> <%= "#{t('.users')} (##{User.count})" %> </h1>

<div class="search-container", id="search-block">
  <%= form_for users_path, data: { turbo_frame: :results }, method: :get do %>
    <%= fields_for 'search' do |search_form| %>
      <div><%= search_form.search_field :email,  placeholder: t('search_form.search_by_email'),
                            oninput: 'this.form.requestSubmit()', autofocus: true, autocomplete: 'off' %></div>
      <div>
        <%= search_form.label :role, t('search_form.search_by_role') %>
        <%= search_form.select(:role, Role.all.collect { |role| role.name}, { include_blank: t('search_form.select_role') }) %>
      </div>
      <div><%= t('search_form.user_date_range') %></div>
      <div>
        <%= search_form.label :created_at_to, t('search_form.to') %>
        <%= search_form.date_select :created_at_to, include_blank: true %>
      </div>
      <div>
        <%= search_form.label :created_at_from, t('search_form.from') %>
        <%= search_form.date_select :created_at_from, include_blank: true %>
      </div>
      <div><%= t('search_form.order_date_range') %></div>
      <div>
        <%= search_form.label :order_created_at_to, t('search_form.to') %>
        <%= search_form.date_select :order_created_at_to, include_blank: true %>
      </div>
      <div>
        <%= search_form.label :order_created_at_from, t('search_form.from') %>
        <%= search_form.date_select :order_created_at_from, include_blank: true %>
      </div>
      <div>
        <%= search_form.label :sort, t('search_form.sort') %>
        <div class='switch-container'>
          <%= search_form.label :sort_email, t('search_form.sort_email'), class: 'lable-name' %>
          <label class='arrow'>
            <%= search_form.radio_button :sort, 'email asc', checked: 'checked' %>
            <%= image_tag('arrow_up.svg', alt: t('buttons.arrow_up')) %>
          </label>
          <label class='arrow'>
            <%= search_form.radio_button :sort, 'email desc' %>
            <%= image_tag('arrow_down.svg', alt: t('buttons.arrow_down')) %>
          </label>
          <%= search_form.label :sort_reg, t('search_form.sort_registration'), class: 'lable-name' %>

          <label class='arrow'>
            <%= search_form.radio_button :sort, 'created_at asc' %>
            <%= image_tag('arrow_up.svg', alt: t('buttons.arrow_up')) %>
          </label>
          <label class='arrow'>
            <%= search_form.radio_button :sort, 'created_at desc' %>
            <%= image_tag('arrow_down.svg', alt: t('buttons.arrow_down')) %>
          </label>
        </div>
      </div>
    <% end %>
    <div class="btn-container">
      <%= button_tag t('buttons.search'), class: 'submit-btn' %>
    </div>
  <% end %>
<hr>
</div>
<%= turbo_frame_tag :results, data: { turbo_action: 'advsnce' } do %>
  <div id="users"></div>
  <%= turbo_frame_tag :pagination, loading: :lazy, src: users_path(format: :turbo_stream, search: params[:search]&.to_unsafe_h) %>
<% end %>

app/views/admins/index.turbo_stream.erb
<%= turbo_stream.append :users do %>
  <% index = 0 %>
  <% @users.each do |user| %>
    <% index += 1 %>
    <% tbody_class = index.even? ? 'user-even' : 'user-odd' %>
    <div class="<%= tbody_class %>">
      <ul class="user_info">
        <li><%== "Id/email: #{user.id}/#{highlight(user.email, params.dig(:search, :email))}" %></li>
        <li><%= "#{t('.created_at')}: #{user.created_at}" %></li>
        <li><%= "#{t('.roles')}: #{user.roles.pluck(:name).sort}" %></li>
        <li><%= link_to t('buttons.edit'), user_edit_path(user) %></li>
      </ul>
      <div class="user_orders">
        <% if user.orders.any? %>
          <%= link_to "#{t('.quantity_of_orders')} (#{user.orders.size})", orders_path(user_id: user.id) %>
          <% user.orders.reverse.first(5).each do |order|  %>
            <div><%= link_to "#{t('.date')}: #{order.created_at.strftime("%d/%m/%Y %k:%M")} # #{t('.cost')}: #{order.cost}", order_path(order) %></div>
          <% end %>
        <% else %>
          <%= t('.no_order') %>
        <% end %>
      </div>
      <div class="user_block">
        <%= button_to t('.block_account'), user_update_path(user), params: {set_user_role: :blocked}, form: { data: { confirm: t('.confirmation') } }, method: :put %>
      </div>
    </div>
  <% end %>
<% end %>

<% if @pagy.next.present?%>
  <%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, loading: :lazy, src: users_path(format: :turbo_stream, page: @pagy.next, search: params[:search]&.to_unsafe_h) %>
  <% end %>
<% end %>
  

app/views/admins/show.html.erb
<h1><%= t('.user') %></h1>
<p><%= @user.email %></p>
<p><%= @user.roles.pluck(:name) if @user.has_role? :admin %></p>
<p><%= link_to t('.edit_profile'), edit_user_registration_path, data: { turbo: false } %></p>

<%= link_to t('buttons.back'), :back %>