config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', as: 'home'
  get 'static_pages/about_project', as: 'about_project'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :product_categories
    resources :cart_items, only: [:create, :update, :destroy]
    resources :carts, only: [:show]
    resources :orders, only: [:index, :show, :create]
    get     'customers',          to: 'admins#index',   as: 'users'
    get     'customer/:id',       to: 'admins#show',    as: 'user'
    get     'customer/:id/edit',  to: 'admins#edit',    as: 'user_edit'
    put     'customer/:id',       to: 'admins#update',  as: 'user_update'
    delete  'customer/:id',       to: 'admins#destroy', as: 'user_destroy'
    
    post  'csv_accept',   to: 'products#csv_accept'
    put   'bulk_update',  to: 'products#bulk_update'
    get   'csv_export',   to: 'products#csv_export'

    devise_for :users, controllers: {
      confirmations:  'users/confirmations', 
      passwords:      'users/passwords', 
      registrations:  'users/registrations',
      sessions:       'users/sessions'
    }
    root "static_pages#home"
    resources :products do
      member do
        delete :purge_one_attachment
        delete :purge_all_attachments
      end 
    end
  end
  # delete 'PurgeAttachments/:id/purge', to: 'purge_attachments#purge_one_attachment', as: 'purge_one_attachment'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-container">
    <div class="gap-footer"></div>
    <div class="footer-container">
      <div class="contacts">
        <h3>Author</h3>
        <ul>
          <li><%= link_to 'Phone 1: +38(050)-8026-450', about_project_path %></li>
          <li><%= link_to 'Viber, Telegram, WhatsApp', about_project_path %></li>
          <li><%= link_to "email: s19f84@gmail.com", about_project_path %></li>
        </ul>
      </div>
      <div class="info">
        <h3>Information</h3>
        <ul>
          <li><%= link_to 'Info I', about_project_path %></li>
          <li><%= link_to 'Info II', about_project_path %></li>
          <li><%= link_to 'Info III', about_project_path %></li>
        </ul>
      </div>
      <div class="service">
        <h3>Service</h3>
        <ul>
          <li><%= link_to 'Service A', about_project_path %></li>
          <li><%= link_to 'Service B', about_project_path %></li>
          <li><%= link_to 'Service C', about_project_path %></li>
        </ul>
      </div>
      <div class="account">
        <% if current_user.nil? %>
          <h3><%= link_to 'My account', new_user_session_path, method: :post %></h3>
        <% else %>
          <h3>My account</h3>
          <ul>
            <li><%= link_to 'My account', user_path(current_user.id) %></li>
            <li><%= link_to 'Order history', orders_path %></li>
            <li><%= link_to 'Cart', cart_path(current_user.cart.id) %></li>
          </ul>
        <% end %>
      </div>
      <div class="social">
        <h3>Social networks</h3>
        <ul>
          <li><%= link_to 'Facebook', about_project_path %></li>
          <li><%= link_to 'Telegram', about_project_path %></li>
          <li><%= link_to 'Instagram', about_project_path %></li>
        </ul>
      </div>
    </div>
    <div class="gap-footer"></div>
  </div>
    <div class="footer-basement">
    </div>
</footer>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-container">
    <div class="mobile-menu-icons">
      <%= image_tag('burger_menu.svg', alt: t('.burger_menu'), class: 'mobile-menu', id: 'mobile-cta' ) %>
      <%= image_tag('filter.svg', alt: t('.filter'), class: 'mobile-filter', id: 'mobile-filter-cta' ) %>
      <%= image_tag('search.svg', alt: t('.search'), class: 'mobile-search', id: 'mobile-search-cta' ) %>
      <%= link_to_unless_current(image_tag('uk.png', alt: t('.uk_flag'), class: 'mobile-uk'), url_for(locale: :uk)) %>
      <%= link_to_unless_current(image_tag('en.png', alt: t('.en_flag'), class: 'mobile-en'), url_for(locale: :en)) %>
    </div>
    <nav>
      <%= image_tag('exit.svg', alt: t('.exit_menu'), class: 'mobile-menu-exit', id: 'mobile-exit' ) %>
      <div>
        <%= render 'shared/link_block' %>
        <div></div>
        <%= render 'shared/registration_block' %>
      </div>
    </nav>

    <div class="gap-1"></div>
    <div class="menu-container">
      <div class="category"><%= t('.menu') %></div>
      <div class="dropdown-container">
        <%= render 'shared/link_block' %>
      </div>
    </div>
    <div class="link-block">
      <%= render 'shared/link_block' %>
    </div>
    <div class="gap-1"></div>
      <% link_to t('.menu', default: 'no translate'), '#', class: 'header-link' %>
    <div class="devise-menu">
      <%= render 'shared/registration_block' %> 
    </div>
    <div class="block-cart">
      <% if user_signed_in? %>
        <div id="cart">
          <span id="cart-total">
            <%= link_to (image_tag('icon_basket.png', alt: t('.cart'), class: 'header-link' )), cart_path(current_user.cart.id)%>
            <% unless current_user.nil? %>
              <% counter = current_user.cart.cart_items.count %>
              <% if counter > 0 %> 
                <span class="cart-quantity" id="cart_quantity"><%= counter %></span>
              <% end %>
            <% end %>
          </span>
        </div>
      <% end %>
      
    </div>
    <div class="languages">
      <div><%= link_to_unless_current 'UK', url_for(locale: :uk), class: 'header-link' %></div>
      <div class="vertical-rod"><span> | </span></div>
      <div><%= link_to_unless_current 'EN', url_for(locale: :en), class: 'header-link' %></div>
    </div>
  </div>
  
</div>

app/views/shared/_link_block.html.erb
<div><%= link_to t('shared.header.about_project'), about_project_path, class: 'header-link' %></div>  
<div><%= link_to t('breadcrumbs.home'), root_path, class: 'header-link' %></div>  
<% if user_signed_in? %>
  <div><%= link_to t('shared.header.my_account'), user_path(current_user.id), class: 'header-link' %></div>  
  <div><%= link_to t('shared.header.order_history'), orders_path, class: 'header-link' %></div>  
  <% if current_user.has_role? :admin  %>
    <div><%= link_to(t('buttons.users'), users_path, class: 'header-link') %></div>
  <% end %>
<% end %>

app/views/shared/_messages.html.erb
  <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: message_type %>
  <% end %>

app/views/shared/_pagy_nav.html.erb
<div>
  <%== pagy_nav(@pagy) %>
  <%= link_to_unless_current "5", users_path(items: 5) %>
  <%= link_to_unless_current "10", users_path(items: 10) %>
  <%= link_to_unless_current "20", users_path(items: 10) %>
  <%= link_to_unless_current "50", users_path(items: 50) %>
</div>

app/views/shared/_recaptcha.erb
<%= content_for :recaptcha_js do %>
  <%= include_recaptcha_js %>
<% end %>

<% if params[:show_checkbox_recaptcha] %>
  <%= recaptcha_tags %>
<% else %>
  <%= recaptcha_action(action) %>
<% end %>

app/views/shared/_registration_block.html.erb
<% if user_signed_in? %>
  <div><%= link_to t('buttons.sign_out'), destroy_user_session_path, data: {turbo_method: :delete}, class: 'header-link' %></div>
<% else %>
  <div><%= link_to t('buttons.sign_in'), new_user_session_path, data: { turbo: false }, class: 'header-link' %></div>
  <div class="vertical-rod"><span><%= ' | ' %></span></div>
  <div><%= link_to t('buttons.sign_up'), new_user_registration_path, data: { turbo: false }, class: 'header-link' %></div>
<% end %>