config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', as: 'home'
  get 'static_pages/about_project', as: 'about_project'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :product_categories
    resources :cart_items, only: [:create, :update, :destroy]
    resources :carts, only: [:show]
    resources :orders, only: [:index, :show, :create]
    get     'customers',          to: 'admins#index',   as: 'users'
    get     'customer/:id',       to: 'admins#show',    as: 'user'
    get     'customer/:id/edit',  to: 'admins#edit',    as: 'user_edit'
    put     'customer/:id',       to: 'admins#update',  as: 'user_update'
    delete  'customer/:id',       to: 'admins#destroy', as: 'user_destroy'
    
    post  'csv_accept',   to: 'products#csv_accept'
    put   'bulk_update',  to: 'products#bulk_update'
    get   'csv_export',   to: 'products#csv_export'

    devise_for :users, controllers: {
      confirmations:  'users/confirmations', 
      passwords:      'users/passwords', 
      registrations:  'users/registrations',
      sessions:       'users/sessions'
    }
    root "static_pages#home"
    resources :products do
      member do
        delete :purge_one_attachment
        delete :purge_all_attachments
      end 
    end
  end
  # delete 'PurgeAttachments/:id/purge', to: 'purge_attachments#purge_one_attachment', as: 'purge_one_attachment'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  has_many :products

  validates :name, length: { maximum: 100, too_long: '%<count>s characters is max allowed' }, presence: true
  validates :description, length: { in: 3..1200,
                                    too_long: '%<count>s characters is max allowed',
                                    too_short: '%<count>s characters is min allowed' }

  accepts_nested_attributes_for :products, allow_destroy: true
end

app/controllers/product_categories_controller.rb
# frozen_string_literal: true

class ProductCategoriesController < ApplicationController
  before_action :product_category, only: %i[show edit update destroy]
  before_action :authorize_product_category, only: %i[edit update destroy]
  add_breadcrumb I18n.t('breadcrumbs.products'), :product_categories_path, only: %i[index show new edit]

  def index
    product_categories
  end

  def show
    add_breadcrumb product_category.name, product_category_path(product_category)
    render 'products/index', params: { product_category_id: product_category.id }
  end

  def new
    @product_category = ProductCategory.new
    add_breadcrumb I18n.t('breadcrumbs.product_category_new'), new_product_category_path
    authorize_product_category
  end

  def create
    @product_category = ProductCategory.new(product_category_params)
    authorize_product_category
    if @product_category.valid?
      @product_category.save
      redirect_back fallback_location: product_categories_path
    else
      render :new, notice: I18n.t('controllers.products.incorrect_input')
    end
  end

  def edit
    product_categories
    @product_category ||= ProductCategory.includes(products: { product_inventory: %i[id product_id
                                                                                     quantity] }).where(id: params[:id])
    @products = Product.where(product_category: @product_category.id).includes(:product_inventory)
    add_breadcrumb I18n.t('breadcrumbs.product_category_edit'), edit_product_category_path(product_category)
  end

  def update
    authorize_product_category
    if product_category.update(product_category_params)
      redirect_to product_categories_path, notice: I18n.t('controllers.product_categories.updated')
    else
      render :edit, status: I18n.t('controllers.products.incorrect_input')
    end
  end

  def destroy
    authorize_product_category
    redirect_to product_categories_path, notice: I18n.t(safe_delete(product_category))
  end

  private

  def product_category
    @product_category ||= ProductCategory.find(params[:id])
  end

  def authorize_product_category
    authorize @product_category
  end

  def safe_delete(category_item)
    associated_products = Product.where(product_category_id: category_item.id)
    if associated_products == []
      category_item.delete
      'controllers.product_categories.deleted'
    else
      unsorted = unsorted_category
      associated_products.map do |product|
        product.update(product_category_id: unsorted.id)
      end
      if category_item == unsorted
        'controllers.product_categories.deletion_forbidden'
      else
        category_item.delete
        'controllers.product_categories.deleted'
      end
    end
  end

  def product_category_params
    params.require(:product_category).permit(:name, :description, :source, :product_category_id, :locale, :id,
                                             search: %i[name cost_from cost_to sort product_category_id],
                                             products_attributes: [:name, :price, :id, :_destroy,
                                                                   { product_inventory_attributes: %i[quantity id] }])
  end
end

app/views/product_categories/_bulk_update.html.erb
<% if @products.any? %>
  <%= form_for :products, url: bulk_update_path, html: { method: :put }  do |form| %>
    <table>
      <thead>
        <tr>
          <th><%= 'id' %></th>
          <th><%= t('.name') %></th>
          <th><%= t('.sku') %></th>
          <th><%= t('.price') %></th>
          <th><%= t('.quantity') %></th>
          <th><%= t('.category') %></th>
          <th><%= t('buttons.delete') %></th>
        </tr>
      </thead>
      <% @products.each_with_index do |product, index| %>
        <%= fields_for "product[#{product.id}]", product do |product_fields| %>
          <% tbody_class = index.even? ? 'row-even' : 'row-odd' %>
          <tbody class="<%= tbody_class %>">
            <td><%= product_fields.text_field :id, value: product.id, readonly: true %></td>
            <td><%= product_fields.text_field :name, value: product.name,  required: true, label: false %></td>
            <td><%= product_fields.text_field :sku, value: product.sku,  required: true, label: false %></td>
            <td><%= product_fields.text_field :price, as: :decimal, value: product.price, label: false %></td>
            <td>
              <%= product_fields.fields_for :product_inventory do |product_inventory| %>
                <%= product_inventory.text_field :quantity, value: product.product_inventory.quantity, validate: { only_integer: true }, required: true, label: false %>
              <% end %>
            </td>
            <td><%= product_fields.select :product_category_id, @product_categories.pluck('name'), selected: @product_category.name %></td>
            <td><%= product_fields.check_box :dstr, checked: false %></td>
          </tbody>
        <% end %>
      <% end %>
    </table>
    <div class="btn-container">
      <%= form.button :submit, class: 'submit-btn' %>
    </div>
  <% end %>
<% else %>
  <h2>
    <%= t('.empty_category') %>
    <%= link_to t('.add_new_item'), new_product_path %>
  </h2>
<% end %>

app/views/product_categories/_csv_import.html.erb
<div>
  <%= form_tag csv_accept_path, method: :post, multipart: true do %>
    <%= file_field_tag :file, accept: ".csv" %>
    <%= submit_tag t('buttons.csv_import') %>
  <% end %>
  <p><%= t('buttons.csv_sep') %></p>
</div>

app/views/product_categories/edit.html.erb
<h1><%= "#{t('breadcrumbs.product_category_edit')} #{@product_category.name}" %></h1>
<div>
  <%= simple_form_for @product_category, data: { turbo: false } do |form| %>
    <%= form.input :name, required: true %>
    <%= form.input :description %>
    
    <div class="btn-container">
      <%= form.button :submit, class: 'submit-btn' %>
    </div>
  <% end %>
</div>

<div>
  <%= render 'bulk_update' %>
</div>

<div class="show-control">
  <span><%= link_to t('buttons.back'), :back %>  |  <%= link_to t('buttons.link_to_index'), product_categories_path %></span>
</div>

app/views/product_categories/index.html.erb
<h1><%= t('layouts.application.categories') %></h1>

<div class="csv-block">
  <% if current_user_admin? %>
    <div><%= link_to "#{t('.add_new_category')}", new_product_category_path %></div>
    <%= render 'csv_import' %>
    <div>
      <form action="<%= csv_export_path(format: 'csv') %>" method="get" target="_self">
        <%= fields_for 'search' do |search_form| %> 
          <%= search_form.select(:product_category_name, ProductCategory.all.order(name: :asc).collect { |cat| cat.name}, { include_blank: t('search_form.select_all_cat') }) %>
        <% end %>
        <%= button_tag t('buttons.csv_export') %>
        <%= hidden_field_tag('format', 'csv') %>
      </form>
    </div>
  <% end %>
</div>  
<div class="product-index">
  <% @product_categories.each do |product_category| %>
    <div class="product-item">
      <div class="item-img">
        <% if product_category.products.first%>
          <% if product_category.products.first.images.attached? %>
            <%= link_to (image_tag (product_category.products.first.images.first.variant(resize_to_limit: [300, 300]))),
                                    product_category_path(product_category, product_category_id: product_category.id, source: 'index')%>
          <% else %>
            <% image_path = 'no-image-icon-23483.png' %>
            <%= link_to (image_tag image_path, alt: "#{t('products.product_picture')} #{product_category.name}"),
                                    product_category_path(product_category, product_category_id: product_category.id, source: 'index') %>
          <% end %>
        <% end %>
      </div>
      <div class="item-description">
              <div class="name-sku font-bolt-medium">
                <%= link_to(product_category.name, product_category_path(product_category, { product_category_id: product_category.id, source: 'index' } )) %>
              </div>
        <% if current_user_admin? %>
          <div class="name-sku">
            <div class="item-name"><%= link_to(t('buttons.edit'), edit_product_category_path(product_category)) %></div>
            <div class="item-code">
              <%= link_to(t('buttons.delete'), product_category_path(product_category), data: {turbo_method: :delete, turbo_confirm: 'Sure?'}) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/product_categories/new.html.erb
<h1> <%= t('.title') %> </h1>
<div>
  <%= simple_form_for @product_category, data: { turbo: false } do |form| %>
    <%= form.input :name, required: true %>
    <%= form.input :description %>
    <div class="btn-container">
      <%= form.button :submit, class: 'submit-btn' %>
    </div>
  <% end %>
</div>
<div class="show-control">
  <span><%= link_to t('buttons.back'), :back %>  |  <%= link_to t('buttons.link_to_index'), product_categories_path %></span>
</div>