config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', as: 'home'
  get 'static_pages/about_project', as: 'about_project'
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :product_categories
    resources :cart_items, only: [:create, :update, :destroy]
    resources :carts, only: [:show]
    resources :orders, only: [:index, :show, :create]
    get     'customers',          to: 'admins#index',   as: 'users'
    get     'customer/:id',       to: 'admins#show',    as: 'user'
    get     'customer/:id/edit',  to: 'admins#edit',    as: 'user_edit'
    put     'customer/:id',       to: 'admins#update',  as: 'user_update'
    delete  'customer/:id',       to: 'admins#destroy', as: 'user_destroy'
    
    post  'csv_accept',   to: 'products#csv_accept'
    put   'bulk_update',  to: 'products#bulk_update'
    get   'csv_export',   to: 'products#csv_export'

    devise_for :users, controllers: {
      confirmations:  'users/confirmations', 
      passwords:      'users/passwords', 
      registrations:  'users/registrations',
      sessions:       'users/sessions'
    }
    root "static_pages#home"
    resources :products do
      member do
        delete :purge_one_attachment
        delete :purge_all_attachments
      end 
    end
  end
  # delete 'PurgeAttachments/:id/purge', to: 'purge_attachments#purge_one_attachment', as: 'purge_one_attachment'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates_presence_of :name, message: I18n.t('activerecord.errors.models.product.attributes.name.presence')
  # validates :name, presence: true
  validates :name, length: { maximum: 100, too_long: '%<count>s characters is max allowed' }, presence: true
  validates :description, length: { in: 3..1200,
                                    too_long: '%<count>s characters is max allowed',
                                    too_short: '%<count>s characters is min allowed' }
  validates :price, numericality: true, allow_blank: true
  # validates :images, content_type:  { in: %w[image/jpeg image/gif image/png],
  #                                     message: "must be a valid image format" },
  #                     size:
  #                                   { less_than: 5.megabytes,
  #                                     message: "should be less than 5MB" }
  belongs_to :product_category

  has_many_attached :images
  has_many :cart_items, dependent: :destroy
  has_one :product_inventory, dependent: :destroy

  after_create :add_product_inventory

  def self.product_search(search)
    if search
      sort_key    = sort_key_order(search[:sort])[:key]
      sort_order  = sort_key_order(search[:sort])[:order]

      search[:cost_from] ||= ''
      search[:cost_to] ||= ''
      cost_from = search[:cost_from]  == '' ? 0 : search[:cost_from]
      cost_to   = search[:cost_to]    == '' ? 1_000_000_000_000 : search[:cost_to]
      product = Product.includes(:product_inventory, [:images_attachments])
                       .where('name ILIKE ?', "%#{search[:name].downcase if search[:name]}%")
                       .where('price BETWEEN ? AND ?', cost_from, cost_to)
                       .distinct
                       .order(sort_key => sort_order)
      unless search[:product_category_id].blank?
        product = product.where(product_category_id: search[:product_category_id])
      end
      product
    else
      Product.includes(:product_inventory, [:images_attachments]).order(created_at: :desc).distinct
    end
  end

  def self.products_in_cart(user_id)
    user = User.includes(cart: :cart_items).where(id: user_id).sample
    products_in_cart = []
    user.cart.cart_items.map { |cart_item| products_in_cart << cart_item.product_id }
    products_in_cart
  end

  def add_product_inventory
    ProductInventory.create(product_id: id, quantity: 0)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :product_categories, only: %i[new edit]
  before_action :product, only: %i[edit update destroy]
  before_action :authorize_product, only: %i[edit]

  add_breadcrumb I18n.t('breadcrumbs.products'), :product_categories_path, only: %i[index show new edit]

  def index
    incoming_params = params.permit(:locale, :format, :page,
                                    search: %i[product_category_id cost_from cost_to name sort])
    @pagy, @products = pagy(Product.product_search(incoming_params[:search]), items: 3)
    @cart_item = CartItem.new
    @products_in_cart = current_user.nil? ? [] : Product.products_in_cart(current_user.id)
    product_category_bread_crumb
  end

  def show
    # product.includes([:blob])
    @cart_item = CartItem.new(product_id: product.id, cart_id: current_user.cart.id) unless current_user.nil?
    product_inventory
    @product_in_cart = Product.products_in_cart(current_user.id).include?(product.id) unless current_user.nil?
    add_breadcrumb @product.product_category.name,
                   product_category_path(@product.product_category_id,
                                         product_category_id: @product.product_category_id)
    add_breadcrumb @product.name, product_path
  end

  def new
    @product = Product.new
    add_breadcrumb I18n.t('breadcrumbs.product_new'), new_product_path
    authorize_product
  end

  def edit; end

  def create
    @product = Product.new(product_params)
    authorize_product
    if @product.valid?
      @product.save
      @product.product_inventory.update(quantity: params[:inventory_quantity][:quantity].to_i)
      redirect_to @product, notice: I18n.t('controllers.products.created')
    else
      render :new, notice: I18n.t('controllers.products.incorrect_input')
    end
  end

  def update
    authorize_product
    if product.update(product_params)
      product_inventory = ProductInventory.find_by(product_id: @product.id)
      stock_quantity =  product_inventory.quantity + params[:inventory_quantity][:quantity].to_i
      stock_quantity = 0 if stock_quantity.negative?
      product_inventory.update(quantity: stock_quantity)
      redirect_to @product, notice: I18n.t('controllers.products.updated')
    else
      render :edit, status: I18n.t('controllers.products.incorrect_input')
    end
  end

  def destroy
    authorize_product
    ::Products::ProductCsv.new.remove_to_unsort?(@product)
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@product) }
    end
  end

  def purge_one_attachment
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_back fallback_location: root_path, notice: I18n.t('controllers.products.image_destroyed')
  end

  def purge_all_attachments
    product.images.purge
    redirect_back fallback_location: root_path, notice: I18n.t('controllers.products.all_images_destroyed')
  end

  def bulk_update
    @product = Product.new
    authorize_product
    ::Products::ProductCsv.new.bulk_product_update(bulk_product_params, product_categories)
    redirect_to product_categories_path, notice: I18n.t('controllers.products.bulk_update')
  end

  def csv_accept
    @product = Product.new
    authorize_product
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    @products = ::Products::ProductCsv.new.csv_import(params[:file], product_categories)
    product_categories
    render :csv_edit, status: 422
  end

  def csv_export
    params.permit(:format, :button, :locale, search: [:product_category_name])
    respond_to do |format|
      format.csv do
        send_data ::Products::ProductCsv.new.csv_export(params[:search][:product_category_name]),
                  filename: "products-#{DateTime.now.strftime('%d%m%Y%H%M')}.csv"
      end
    end
  end

  private

  def products
    @products = Product.includes(:product_category, :product_inventory, [:images_attachments]) # .with_attached_images
  end

  def product
    @product ||= Product.find(params[:id])
  end

  def product_inventories
    @product_inventories ||= ProductInventory.all
  end

  def product_inventory
    @product_inventory ||= ProductInventory.find_by(product_id: product.id)
  end

  def authorize_product
    authorize @product
  end

  def product_category_bread_crumb
    if params[:product_category_id]
      crumb_name = ProductCategory.find(params[:product_category_id]).name
    elsif params[:search] && params[:search][:product_category_id].present?
      crumb_name = ProductCategory.find(params[:search][:product_category_id]).name
    end
    add_breadcrumb crumb_name unless crumb_name.nil?
  end

  def bulk_product_params
    products = params.require(:product).permit!
    products.each do |id, attributes|
      products[id] = attributes.permit(:id, :name, :description, :sku, :price, :product_category_id, :dstr,
                                       :quantity, product_inventory: %i[quantity id])
    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :sku, :price, :product_category_id, :quantity, images: [])
  end
end

app/views/products/_cart_item_form.html.erb
<% if current_user != nil %>
  <div id=<%= "cart_item_form_#{product.id}" %> class="cart-item">
  <% if products_in_cart %>
    <% @cart_item = CartItem.where(product_id: product.id).where(cart_id: current_user.cart.id).sample %>
    <% form_path = cart_item_path(@cart_item.id) %>
    <% submit_button_value = 'simple_form.buttons.product.olready_in_the_cart' %>
    <% submit_button_class = "olready_in_the_cart" %>
  <% else %>
    <% @cart_item = CartItem.new %>
    <% form_path = cart_items_path %>
    <% submit_button_value = 'simple_form.buttons.product.put_to_cart' %>
    <% submit_button_class = "put_to_cart" %>
  <% end %>
    <%= simple_form_for @cart_item, url: form_path, html: {class: "cart-input-form"} do |f| %>
      <%= f.hidden_field :cart_id, value: current_user.cart.id %>
      <%= f.hidden_field :product_id, value: product.id %>
      <% if product.product_inventory.quantity > 0 %>
        <%= f.input :quantity, collection: 1..product.product_inventory.quantity, include_blank: false, input_html: {class: "quantity-input"} %>
        <div>
          <%= f.button :submit, type: :submit, value: t(submit_button_value), class: submit_button_class %>
        </div>
      <% else %>
          <%= f.label :quantity, t('simple_form.labels.product.zero_quantity') %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div><%= link_to t('simple_form.buttons.product.log_in_first'),  new_user_session_path %> </div>
<% end %>

app/views/products/_form.html.erb
<div>
  <%= simple_form_for @product, data: { turbo: false } do |form| %>
    <%= form.input :name %>
    <%= form.input :product_type %>
    <%= form.input :product_code, hint: t('.only_digits') %>
    <%= form.input :description %>
    <div class="form-separator"></div>
    <div class="images-block">
      <% if @product.images.attached? %>
        <% @product.images.each do |img| %>
          <div class="img-item">
            <div><%= image_tag img.variant(resize_to_limit: [100, 100]) %></div>
            <div><%= link_to('Delete image', purge_one_attachment_product_path(img), data: {turbo_method: :delete}) %></div>
            <%= form.hidden_field :images, multiple: true, value: img.signed_id %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="form-separator"></div>
    <% if @product.images.attached? %>
      <%= link_to('delete all images', purge_all_attachments_product_path(@product), data: {turbo_method: :delete}) %>
    <% end %>
    <div class="form-separator"></div>
    <%= form.file_field :images, multiple: true %>
    <div class="btn-container">
      <%= form.button :submit, class: 'submit-btn' %>
    </div>
  <%  end %>
</div>

app/views/products/csv_edit.html.erb
<h1>csv file preview</h1>
<div>
  <% if @products.any? %>
    <%= form_for :products, url: bulk_update_path, local: true, data: { turbo: false }, html: { method: :put }  do |form| %>
      <table>
        <thead>
          <tr>
            <th><%= t('id') %></th>
            <th><%= t('product_categories.edit.name') %></th>
            <th><%= t('product_categories.edit.sku') %></th>
            <th><%= t('product_categories.edit.price') %></th>
            <th><%= t('product_categories.edit.quantity') %></th>
            <th><%= t('product_categories.edit.category') %></th>
            <th><%= t('buttons.delete') %></th>
          </tr>
        </thead>
        <% @products.each_with_index do |product, index| %>
          <%= fields_for "product[#{product[:id]}]", product do |product_fields| %>
            <% tbody_class = index.even? ? 'row-even' : 'row-odd' %>
            <tbody class="<%= tbody_class %>">
              <td><%= product_fields.text_field :id, value: product[:id], readonly: true %></td>
              <td><%= product_fields.text_field :name, value: product[:name],  required: true, label: false %></td>
              <td><%= product_fields.text_field :sku, value: product[:sku],  required: true, label: false %></td>
              <td><%= product_fields.text_field :price, as: :decimal, value: product[:price], label: false %></td>
              <td>
                <%= product_fields.fields_for :product_inventory do |product_inventory| %>
                  <%= product_inventory.text_field :quantity, value: product[:quantity], validate: { only_integer: true }, required: true, label: false %>
                <% end %>
              </td>
              <td><%= product_fields.select :product_category_id, @product_categories.pluck('name'),
                                              selected: @product_categories.where(id: product[:product_category_id]).sample.name %></td>
              <td><%= product_fields.check_box :dstr, checked: false %></td>
            </tbody>
          <% end %>
        <% end %>
      </table>
      <div class="btn-container">
        <%= form.button :submit, class: 'submit-btn' %>
      </div>
    <% end %>
  <% else %>
    <h2>
      <%= t('.empty_category') %>
      <%= link_to t('.add_new_item'), new_product_path %>
    </h2>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1> <%= t('.edit_item') %> </h1>
<div>
  <%= simple_form_for @product, data: { turbo: true } do |form| %>
    <%= form.input :name %>
    <%= form.input :product_category_id, collection: @product_categories %>
    <%= form.input :sku %>
    <%= form.input :price, hint: t('.only_digits') %>
    <%= simple_fields_for :inventory_quantity do |q| %>
      <%= q.input :quantity, as: :integer, hint: t('.add_quantity_to_stock') %>
    <% end %>
    <%= form.input :description %>
    <div class="form-separator"></div>
    <div class="images-block">
      <% if @product.images.attached? %>
        <% @product.images.each do |img| %>
          <div class="img-item">
            <div><%= image_tag img.variant(resize_to_limit: [100, 100]) %></div>
            <div><%= link_to(t('.delete_image'), purge_one_attachment_product_path(img), data: {turbo_method: :delete}) %></div>
            <%= form.hidden_field :images, multiple: true, value: img.signed_id %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="form-separator"></div>
    <% if @product.images.attached? %>
      <%= link_to(t('.delete_all_images'), purge_all_attachments_product_path(@product), data: {turbo_method: :delete}) %>
    <% end %>
    <div class="form-separator"></div>
    <%= form.file_field :images, multiple: true %>
    <div class="btn-container">
      <%= form.button :submit, class: 'submit-btn' %>
    </div>
  <%  end %>
</div>

app/views/products/index.html.erb
<div>
  <h1><%= @product_category.name %></h1>
  <% if current_user_admin? %>
    <h3 class="add-new-item"><%= link_to(t('.add_new_product'), new_product_path) %></h3>
  <% end %>
</div>
<% instance_variable_names.inspect %>
<div class="search-container", id="search-block">
  <%= form_for products_path, data: { turbo_frame: :results }, method: :get do %>
    <%= fields_for 'search' do |search_form| %>
      <div><%= search_form.search_field :name,  placeholder: t('search_form.search_by_name'),
                            oninput: 'this.form.requestSubmit()', autofocus: true, autocomplete: 'off' %>
      </div>
      <div>
        <%= search_form.search_field :cost_from,   placeholder: t('search_form.search_by_order_cost_from'),
                            oninput: 'this.form.requestSubmit()', autofocus: false, autocomplete: 'off' %>
        <span> - </span>
        <%= search_form.search_field :cost_to,     placeholder: t('search_form.search_by_order_cost_to'),
                            oninput: 'this.form.requestSubmit()', autofocus: false, autocomplete: 'off' %>
      </div>
      <div>
        <%= search_form.label :sort, t('search_form.sort') %>
        <div class='switch-container'>
          <%= search_form.label :sort_name, t('search_form.sort_name'), oninput: 'this.form.requestSubmit()', class: 'lable-name' %>
          <label class='arrow'>
            <%= search_form.radio_button :sort, 'name asc', checked: 'checked', oninput: 'this.form.requestSubmit()' %>
            <%= image_tag('arrow_up.svg', alt: t('buttons.arrow_up')) %>
          </label>
          <label class='arrow'>
            <%= search_form.radio_button :sort, 'name desc', oninput: 'this.form.requestSubmit()' %>
            <%= image_tag('arrow_down.svg', alt: t('buttons.arrow_down')) %>
          </label>

          <%= search_form.label :sort_cost, t('search_form.sort_price'), class: 'lable-name' %>
          <label class='arrow'>
            <%= search_form.radio_button :sort, 'price asc', oninput: 'this.form.requestSubmit()' %>
            <%= image_tag('arrow_up.svg', alt: t('buttons.arrow_up')) %>
          </label>
          <label class='arrow'>
            <%= search_form.radio_button :sort, 'price desc', oninput: 'this.form.requestSubmit()' %><%= image_tag('arrow_down.svg', alt: t('buttons.arrow_down')) %>
          </label>
        </div>
      </div>
      <%= search_form.hidden_field :product_category_id, value: @product_category.id %>
    <% end %>
    <div class="btn-container">
      <%= button_tag t('buttons.search'), class: 'submit-btn' %>
    </div>
  <% end %>
</div>

<% search_params = params[:search]&.to_unsafe_h || {} %>
<% search_params[:product_category_id] = params[:product_category_id] if params[:product_category_id] %>
<hr>
<%= turbo_frame_tag :results, data: { turbo_action: 'advance' } do %>
  <div id="products"></div>
  
  <%= turbo_frame_tag :pagination, loading: :lazy, src: products_path(format: :turbo_stream, search: search_params) %>
<% end %>

app/views/products/index.turbo_stream.erb
<turbo-frame id="default">
<%= turbo_stream.append :products do %>
  <% (!current_user.nil? && (current_user.has_role? :admin)) ? current_admin = true : current_admin = false %>
  <div class="product-index">
    <% if @products%>
      <% @products.each do |product| %>
        <div id="product_<%= product.id %>">
          <div class="product-item">
            <div class="item-img">
              <% if product.images.attached? %>
                <%= link_to (image_tag(product.images.first.variant(resize_to_limit: [300, 300]))), product_path(product)%>
              <% else %>
                <% image_path = 'no-image-icon-23483.png' %>
                <%= link_to (image_tag(image_path, alt: "#{t('.product_picture')} #{product.name}")), product_path(product) %>
              <% end %>
            </div>
            <div class="item-description">
              <div class="name-sku">
                <h3><%== link_to highlight(product.name, params.dig(:search, :name)), product_path(product) %></h3>
                <div><%= link_to "#{t(".product_sku")}: #{product.sku}", product_path(product) %></div>
              </div>
              <div class="price-cart">
                <div class="price"><%= link_to "#{t(".product_price")}: #{product.price}", product_path(product)%></div>
                <div class="cart-block">
                  <% @products_in_cart.include?(product.id) ? products_in_cart = true : products_in_cart = false %>
                  <%= render 'cart_item_form', products_in_cart: products_in_cart, product: product %>
                </div>
              </div>
            </div>
            <div class="name-sku">
              <% if current_admin %>
                <div><%= link_to(t('buttons.edit'), edit_product_path(product)) %></div>
                <div><%= link_to(t('buttons.delete'), product_path(product), data: {turbo_method: :delete, turbo_confirm: 'Sure?'}) %></div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h3><%= 'This folder now is empty' %></h3>
    <%end%>
  </div>
<% end %>

<% search_params = params[:search]&.to_unsafe_h || {} %>
<% search_params[:product_category_id] = params[:product_category_id] if params[:product_category_id] %>
<% if @pagy && @pagy.next.present?%>
  <%= turbo_stream.replace :pagination do %>
    
    <%= turbo_frame_tag :pagination, loading: :lazy, src: products_path(format: :turbo_stream, page: @pagy.next, search: search_params) %>
  <% end %>
<% end %>
</turbo-frame>

app/views/products/new.html.erb
<h1> <%= t('.title') %> </h1>
<div>
  <%= simple_form_for @product, data: { turbo: false } do |form| %>
    <%= form.input :name %>
    <%= form.input :product_category_id, collection: @product_categories %>
    <%= form.input :sku %>
    <%= form.input :description %>
    <%= form.input :price, as: :float %>
    <%= simple_fields_for :inventory_quantity do |q| %>
      <%= q.input :quantity, as: :integer %>
    <% end %>
    <div class="form-separator"></div>
    <%= form.file_field :images, multiple: true%>
    <div class="btn-container btn-width-450">
      <%= form.button :submit, class: 'submit-btn' %>
    </div>
    
  <%  end %>
</div>
<div class="show-control">
  <span><%= link_to t('buttons.back'), :back %>  |  <%= link_to t('buttons.link_to_index'), product_categories_path %></span>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<div class="show-container">
  <div class="product-gallery">
    <div class="add-img">
      <% @product.images.each do |image| %>
        <div class="thumbnail">
          <%= image_tag(image.variant(resize_to_limit: [800, 600])) %>
        </div>
      <% end %>
    </div>
    <div class="full-size-image">
      <% if @product.images.attached? %>
        <%= image_tag(@product.images.first.variant(resize_to_limit: [800, 600]), alt: "#{t('.product_picture')} #{@product.name}") %>
      <% else %>
        <% image_path = 'no-image-icon-23483.png' %>
        <%= image_tag(image_path, alt: "#{t('.product_picture')} #{@product.name}") %>
      <% end %>
    </div>
  </div>
  <div class="product-cart-block">
      <div class="product-sku"><%= t('.product_sku') %> <%= @product.sku %></div>
      <div class="product-price"><%= t('.product_price') %> <%= @product.price %></div>
      
      <div class="product-cart-container"><%= render 'cart_item_form', products_in_cart: @product_in_cart, product: @product %></div>
      
  </div>
</div>
<div class="product-description-block">
  <h4><%= t('.description') %></h4>
  <div><%= @product.description %></div>
</div>
<div class="show-control">
  <span><%= link_to t('buttons.back'), :back %>  |  <%= link_to t('buttons.link_to_index'), product_categories_path %></span>
</div>